<Project>
	<ItemDefinitionGroup Condition="'$(Configuration)'=='Sanitised'">
		<ClCompile>
			<!-- Needed for sanitised builds to work properly -->
			<PreprocessorDefinitions>_ANNOTATE_STL;_ENABLE_STL_ANNOTATION_ON_UNSUPPORTED_PLATFORMS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
		</ClCompile>
	</ItemDefinitionGroup>
</Project> 