<Project>
	<ItemDefinitionGroup Condition="'$(Configuration)'!='Release'">
		<ClCompile>
			<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
		<ClCompile>
			<RuntimeLibrary>MultiThreaded</RuntimeLibrary>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition="'$(Configuration)'=='Sanitised'">
		<ClCompile>
			<!-- Needed for sanitised builds to work properly -->
			<PreprocessorDefinitions>_DISABLE_VECTOR_ANNOTATION;_DISABLE_STRING_ANNOTATION;%(PreprocessorDefinitions)</PreprocessorDefinitions>
		</ClCompile>
	</ItemDefinitionGroup>
</Project>