# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  OCLV_VCPKG_CACHE_DIR: "C:/vcpkg_cache"
  VCPKG_BINARY_SOURCES: "clear;files,C:/vcpkg_cache/bin,readwrite"
  X_VCPKG_ASSET_SOURCES: "clear;x-azurl,file://C:/vcpkg_cache/assets,,readwrite"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release, Debug]
        architecture: [x86, x64, ARM64]

      fail-fast: false

    runs-on: windows-latest

    steps:
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: ${{env.OCLV_VCPKG_CACHE_DIR}}
        key: vcpkg-${{matrix.architecture}}-${{matrix.configuration}}

    - name: Create vcpkg Cache Directories
      run: |
        mkdir -p ${{env.OCLV_VCPKG_CACHE_DIR}}/bin
        mkdir -p ${{env.OCLV_VCPKG_CACHE_DIR}}/assets

    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install vcpkg
      run: vcpkg integrate install

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.architecture}} ${{env.SOLUTION_FILE_PATH}}
      
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}-${{matrix.architecture}}-${{matrix.configuration}}
        path: ${{env.OCLV_VCPKG_CACHE_DIR}}
